apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-standalone
      app: database
  template:
    metadata:
      labels:
        name: mongodb-standalone
        app: database
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/mongodb-secret/admin/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongodb-secret/admin/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongodb-secret
          mountPath: /etc/mongodb-secret
          readOnly: true
      volumes:
      - name: mongodb-secret
        secret:
          secretName: mongodb-secret
          items:
          - key: MONGO_ROOT_USERNAME
            path: admin/MONGO_ROOT_USERNAME
            mode: 0444
          - key: MONGO_ROOT_PASSWORD
            path: admin/MONGO_ROOT_PASSWORD
            mode: 0444