apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    name: mongodb-svc
    app: database
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30994
  selector:
    name: mongodb-standalone
    app: database